# Form implementation generated from reading ui file 'spytify-client/Modules/spytify-auth.ui'
# Created by: PyQt5 UI code generator 5.5
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AuthenticationDialog(object):
    def setupUi(self, AuthenticationDialog):
        AuthenticationDialog.setObjectName("AuthenticationDialog")
        AuthenticationDialog.resize(333, 232)
        AuthenticationDialog.setMinimumSize(QtCore.QSize(333, 232))
        AuthenticationDialog.setMaximumSize(QtCore.QSize(333, 232))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Symbol/Icons/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AuthenticationDialog.setWindowIcon(icon)
        AuthenticationDialog.setWindowOpacity(0.9)
        self.usernametext = QtWidgets.QLabel(AuthenticationDialog)
        self.usernametext.setGeometry(QtCore.QRect(30, 40, 61, 21))
        self.usernametext.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usernametext.setObjectName("usernametext")
        self.passwordtext = QtWidgets.QLabel(AuthenticationDialog)
        self.passwordtext.setGeometry(QtCore.QRect(30, 70, 61, 21))
        self.passwordtext.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordtext.setObjectName("passwordtext")
        self.username = QtWidgets.QLineEdit(AuthenticationDialog)
        self.username.setGeometry(QtCore.QRect(100, 40, 161, 23))
        self.username.setClearButtonEnabled(False)
        self.username.setProperty("username", "")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(AuthenticationDialog)
        self.password.setGeometry(QtCore.QRect(100, 70, 161, 23))
        self.password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setProperty("password", "")
        self.password.setObjectName("password")
        self.remember = QtWidgets.QCheckBox(AuthenticationDialog)
        self.remember.setGeometry(QtCore.QRect(100, 100, 85, 21))
        self.remember.setObjectName("remember")
        self.loginbutton = QtWidgets.QPushButton(AuthenticationDialog)
        self.loginbutton.setGeometry(QtCore.QRect(130, 140, 101, 21))
        self.loginbutton.setObjectName("loginbutton")
        self.registerbutton = QtWidgets.QPushButton(AuthenticationDialog)
        self.registerbutton.setGeometry(QtCore.QRect(130, 170, 101, 21))
        self.registerbutton.setObjectName("registerbutton")
        self.mailtext = QtWidgets.QLabel(AuthenticationDialog)
        self.mailtext.setEnabled(True)
        self.mailtext.setGeometry(QtCore.QRect(50, 100, 41, 21))
        self.mailtext.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mailtext.setObjectName("mailtext")
        self.mail = QtWidgets.QLineEdit(AuthenticationDialog)
        self.mail.setEnabled(True)
        self.mail.setGeometry(QtCore.QRect(100, 100, 161, 23))
        self.mail.setProperty("mail", "")
        self.mail.setObjectName("mail")
        self.applybutton = QtWidgets.QPushButton(AuthenticationDialog)
        self.applybutton.setGeometry(QtCore.QRect(40, 160, 111, 21))
        self.applybutton.setObjectName("applybutton")
        self.backbutton = QtWidgets.QPushButton(AuthenticationDialog)
        self.backbutton.setEnabled(True)
        self.backbutton.setGeometry(QtCore.QRect(180, 160, 111, 21))
        self.backbutton.setObjectName("backbutton")
        self.errortext = QtWidgets.QLabel(AuthenticationDialog)
        self.errortext.setGeometry(QtCore.QRect(50, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.errortext.setFont(font)
        self.errortext.setStyleSheet("color: rgb(255, 0, 0);")
        self.errortext.setAlignment(QtCore.Qt.AlignCenter)
        self.errortext.setObjectName("errortext")
        self.successtext = QtWidgets.QLabel(AuthenticationDialog)
        self.successtext.setGeometry(QtCore.QRect(50, 10, 261, 20))
        self.successtext.setStyleSheet("color: rgb(0, 185, 12);")
        self.successtext.setAlignment(QtCore.Qt.AlignCenter)
        self.successtext.setObjectName("successtext")
        self.successtext.raise_()
        self.errortext.raise_()
        self.usernametext.raise_()
        self.passwordtext.raise_()
        self.username.raise_()
        self.password.raise_()
        self.loginbutton.raise_()
        self.registerbutton.raise_()
        self.mailtext.raise_()
        self.mail.raise_()
        self.remember.raise_()
        self.applybutton.raise_()
        self.backbutton.raise_()

        self.retranslateUi(AuthenticationDialog)
        self.registerbutton.clicked.connect(self.loginbutton.hide)
        self.registerbutton.clicked.connect(self.remember.hide)
        self.registerbutton.clicked.connect(self.registerbutton.hide)
        self.registerbutton.clicked.connect(self.applybutton.show)
        self.registerbutton.clicked.connect(self.backbutton.show)
        self.registerbutton.clicked.connect(self.mail.show)
        self.registerbutton.clicked.connect(self.mailtext.show)
        self.backbutton.clicked.connect(self.applybutton.hide)
        self.backbutton.clicked.connect(self.backbutton.hide)
        self.backbutton.clicked.connect(self.mail.hide)
        self.backbutton.clicked.connect(self.mailtext.hide)
        self.backbutton.clicked.connect(self.remember.show)
        self.backbutton.clicked.connect(self.loginbutton.show)
        self.backbutton.clicked.connect(self.registerbutton.show)
        QtCore.QMetaObject.connectSlotsByName(AuthenticationDialog)

    def retranslateUi(self, AuthenticationDialog):
        _translate = QtCore.QCoreApplication.translate
        AuthenticationDialog.setWindowTitle(_translate("AuthenticationDialog", "Spytify - Login"))
        self.usernametext.setText(_translate("AuthenticationDialog", "Username"))
        self.passwordtext.setText(_translate("AuthenticationDialog", "Password"))
        self.remember.setText(_translate("AuthenticationDialog", "Remember"))
        self.loginbutton.setText(_translate("AuthenticationDialog", "Login"))
        self.registerbutton.setText(_translate("AuthenticationDialog", "Sign Up"))
        self.mailtext.setText(_translate("AuthenticationDialog", "e-Mail"))
        self.applybutton.setText(_translate("AuthenticationDialog", "Sign Up"))
        self.backbutton.setText(_translate("AuthenticationDialog", "Cancel"))
        self.errortext.setText(_translate("AuthenticationDialog", "ErrorMessage"))
        self.successtext.setText(_translate("AuthenticationDialog", "SuccessMessage"))

import icons-rc
