# Form implementation generated from reading ui file 'spytify-client/Modules/spytifyGUI.ui'
# Created by: PyQt5 UI code generator 5.5
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName("Interface")
        Interface.resize(889, 610)
        Interface.setMinimumSize(QtCore.QSize(889, 610))
        Interface.setMaximumSize(QtCore.QSize(889, 610))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Symbol/Icons/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Interface.setWindowIcon(icon)
        Interface.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(Interface)
        self.centralwidget.setObjectName("centralwidget")
        self.volumelevel = QtWidgets.QSlider(self.centralwidget)
        self.volumelevel.setGeometry(QtCore.QRect(780, 460, 16, 41))
        self.volumelevel.setStyleSheet("selection-background-color: rgb(204, 204, 204);")
        self.volumelevel.setMaximum(10)
        self.volumelevel.setProperty("value", 10)
        self.volumelevel.setSliderPosition(10)
        self.volumelevel.setOrientation(QtCore.Qt.Vertical)
        self.volumelevel.setObjectName("volumelevel")
        self.playbutton = QtWidgets.QPushButton(self.centralwidget)
        self.playbutton.setEnabled(True)
        self.playbutton.setGeometry(QtCore.QRect(590, 460, 41, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Button/Icons/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playbutton.setIcon(icon1)
        self.playbutton.setIconSize(QtCore.QSize(30, 30))
        self.playbutton.setObjectName("playbutton")
        self.stopbutton = QtWidgets.QPushButton(self.centralwidget)
        self.stopbutton.setEnabled(True)
        self.stopbutton.setGeometry(QtCore.QRect(450, 460, 41, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Button/Icons/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopbutton.setIcon(icon2)
        self.stopbutton.setIconSize(QtCore.QSize(30, 30))
        self.stopbutton.setObjectName("stopbutton")
        self.pausebutton = QtWidgets.QPushButton(self.centralwidget)
        self.pausebutton.setEnabled(True)
        self.pausebutton.setGeometry(QtCore.QRect(590, 460, 41, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pausebutton.setFont(font)
        self.pausebutton.setAutoFillBackground(False)
        self.pausebutton.setStyleSheet("")
        self.pausebutton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Button/Icons/Pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pausebutton.setIcon(icon3)
        self.pausebutton.setIconSize(QtCore.QSize(30, 30))
        self.pausebutton.setObjectName("pausebutton")
        self.nextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.nextbutton.setEnabled(True)
        self.nextbutton.setGeometry(QtCore.QRect(630, 460, 41, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Button/Icons/Coming.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextbutton.setIcon(icon4)
        self.nextbutton.setIconSize(QtCore.QSize(30, 30))
        self.nextbutton.setObjectName("nextbutton")
        self.previousbutton = QtWidgets.QPushButton(self.centralwidget)
        self.previousbutton.setEnabled(True)
        self.previousbutton.setGeometry(QtCore.QRect(550, 460, 41, 41))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Button/Icons/Previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousbutton.setIcon(icon5)
        self.previousbutton.setIconSize(QtCore.QSize(30, 30))
        self.previousbutton.setObjectName("previousbutton")
        self.lengthbar = QtWidgets.QProgressBar(self.centralwidget)
        self.lengthbar.setGeometry(QtCore.QRect(350, 521, 521, 20))
        self.lengthbar.setMouseTracking(True)
        self.lengthbar.setStyleSheet("selection-background-color: rgb(204, 204, 204);\n"
"")
        self.lengthbar.setMaximum(1000)
        self.lengthbar.setProperty("value", 0)
        self.lengthbar.setTextVisible(False)
        self.lengthbar.setObjectName("lengthbar")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 321, 481))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setObjectName("tabWidget")
        self.library = QtWidgets.QWidget()
        self.library.setObjectName("library")
        self.tableWidget = QtWidgets.QTableWidget(self.library)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 281, 481))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget.verticalHeader().setMinimumSectionSize(20)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Playlist/Icons/Library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.library, icon6, "")
        self.playlist1 = QtWidgets.QWidget()
        self.playlist1.setObjectName("playlist1")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Playlist/Icons/NewPlaylist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.playlist1, icon7, "")
        self.playlist2 = QtWidgets.QWidget()
        self.playlist2.setObjectName("playlist2")
        self.tabWidget.addTab(self.playlist2, icon7, "")
        self.playlist3 = QtWidgets.QWidget()
        self.playlist3.setObjectName("playlist3")
        self.tabWidget.addTab(self.playlist3, icon7, "")
        self.songname = QtWidgets.QLabel(self.centralwidget)
        self.songname.setGeometry(QtCore.QRect(350, 430, 521, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.songname.setFont(font)
        self.songname.setAlignment(QtCore.Qt.AlignCenter)
        self.songname.setObjectName("songname")
        self.welcometext = QtWidgets.QLabel(self.centralwidget)
        self.welcometext.setEnabled(True)
        self.welcometext.setGeometry(QtCore.QRect(720, 10, 91, 20))
        self.welcometext.setMidLineWidth(0)
        self.welcometext.setScaledContents(False)
        self.welcometext.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.welcometext.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.welcometext.setObjectName("welcometext")
        self.usericon = QtWidgets.QGraphicsView(self.centralwidget)
        self.usericon.setGeometry(QtCore.QRect(820, 10, 41, 41))
        self.usericon.setStyleSheet("border-image: url(:/Symbol/Icons/User.png);")
        self.usericon.setObjectName("usericon")
        self.soundbutton = QtWidgets.QPushButton(self.centralwidget)
        self.soundbutton.setGeometry(QtCore.QRect(730, 460, 41, 41))
        self.soundbutton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Button/Icons/Sound.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.soundbutton.setIcon(icon8)
        self.soundbutton.setIconSize(QtCore.QSize(35, 35))
        self.soundbutton.setObjectName("soundbutton")
        self.usertext = QtWidgets.QLabel(self.centralwidget)
        self.usertext.setEnabled(True)
        self.usertext.setGeometry(QtCore.QRect(720, 30, 91, 20))
        self.usertext.setScaledContents(False)
        self.usertext.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usertext.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.usertext.setObjectName("usertext")
        self.randombutton = QtWidgets.QPushButton(self.centralwidget)
        self.randombutton.setEnabled(True)
        self.randombutton.setGeometry(QtCore.QRect(500, 460, 41, 41))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Button/Icons/Random.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.randombutton.setIcon(icon9)
        self.randombutton.setIconSize(QtCore.QSize(35, 35))
        self.randombutton.setObjectName("randombutton")
        self.repeatbutton = QtWidgets.QPushButton(self.centralwidget)
        self.repeatbutton.setEnabled(True)
        self.repeatbutton.setGeometry(QtCore.QRect(680, 460, 41, 41))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Button/Icons/Repeat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.repeatbutton.setIcon(icon10)
        self.repeatbutton.setIconSize(QtCore.QSize(35, 35))
        self.repeatbutton.setObjectName("repeatbutton")
        self.errortext = QtWidgets.QLabel(self.centralwidget)
        self.errortext.setGeometry(QtCore.QRect(50, 550, 281, 16))
        self.errortext.setStyleSheet("color: rgb(255, 0, 0);")
        self.errortext.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.errortext.setObjectName("errortext")
        self.searchbutton = QtWidgets.QPushButton(self.centralwidget)
        self.searchbutton.setGeometry(QtCore.QRect(250, 20, 80, 23))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Symbol/Icons/Search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchbutton.setIcon(icon11)
        self.searchbutton.setIconSize(QtCore.QSize(10, 10))
        self.searchbutton.setObjectName("searchbutton")
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(40, 20, 211, 23))
        font = QtGui.QFont()
        font.setItalic(False)
        self.search.setFont(font)
        self.search.setObjectName("search")
        self.mutebutton = QtWidgets.QPushButton(self.centralwidget)
        self.mutebutton.setGeometry(QtCore.QRect(730, 460, 41, 41))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Button/Icons/Mute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mutebutton.setIcon(icon12)
        self.mutebutton.setIconSize(QtCore.QSize(35, 35))
        self.mutebutton.setObjectName("mutebutton")
        self.coverlabel = QtWidgets.QLabel(self.centralwidget)
        self.coverlabel.setGeometry(QtCore.QRect(350, 60, 521, 361))
        self.coverlabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.coverlabel.setText("")
        self.coverlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.coverlabel.setObjectName("coverlabel")
        self.playingtext = QtWidgets.QLabel(self.centralwidget)
        self.playingtext.setGeometry(QtCore.QRect(350, 520, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.playingtext.setFont(font)
        self.playingtext.setAlignment(QtCore.Qt.AlignCenter)
        self.playingtext.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.playingtext.setObjectName("playingtext")
        self.crossrandom = QtWidgets.QPushButton(self.centralwidget)
        self.crossrandom.setEnabled(True)
        self.crossrandom.setGeometry(QtCore.QRect(500, 460, 41, 41))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Button/Icons/CrossRandom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.crossrandom.setIcon(icon13)
        self.crossrandom.setIconSize(QtCore.QSize(35, 35))
        self.crossrandom.setObjectName("crossrandom")
        self.crossrepeat = QtWidgets.QPushButton(self.centralwidget)
        self.crossrepeat.setEnabled(True)
        self.crossrepeat.setGeometry(QtCore.QRect(680, 460, 41, 41))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Button/Icons/CrossRepeat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.crossrepeat.setIcon(icon14)
        self.crossrepeat.setIconSize(QtCore.QSize(35, 35))
        self.crossrepeat.setObjectName("crossrepeat")
        self.animationtext = QtWidgets.QLabel(self.centralwidget)
        self.animationtext.setGeometry(QtCore.QRect(851, 520, 20, 21))
        self.animationtext.setAlignment(QtCore.Qt.AlignCenter)
        self.animationtext.setObjectName("animationtext")
        self.crossrepeat.raise_()
        self.crossrandom.raise_()
        self.mutebutton.raise_()
        self.soundbutton.raise_()
        self.coverlabel.raise_()
        self.pausebutton.raise_()
        self.volumelevel.raise_()
        self.playbutton.raise_()
        self.stopbutton.raise_()
        self.nextbutton.raise_()
        self.previousbutton.raise_()
        self.lengthbar.raise_()
        self.tabWidget.raise_()
        self.songname.raise_()
        self.welcometext.raise_()
        self.usericon.raise_()
        self.usertext.raise_()
        self.randombutton.raise_()
        self.repeatbutton.raise_()
        self.errortext.raise_()
        self.searchbutton.raise_()
        self.search.raise_()
        self.playingtext.raise_()
        self.animationtext.raise_()
        Interface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Interface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 20))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        Interface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Interface)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        Interface.setStatusBar(self.statusbar)
        self.actionLogOut = QtWidgets.QAction(Interface)
        self.actionLogOut.setObjectName("actionLogOut")
        self.actionExit = QtWidgets.QAction(Interface)
        self.actionExit.setObjectName("actionExit")
        self.menuAction.addAction(self.actionLogOut)
        self.menuAction.addAction(self.actionExit)
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Interface)
        self.tabWidget.setCurrentIndex(0)
        self.playbutton.clicked.connect(self.playbutton.hide)
        self.soundbutton.clicked.connect(self.soundbutton.hide)
        self.soundbutton.clicked.connect(self.mutebutton.show)
        self.mutebutton.clicked.connect(self.soundbutton.show)
        self.mutebutton.clicked.connect(self.mutebutton.hide)
        self.playbutton.clicked.connect(self.pausebutton.show)
        self.pausebutton.clicked.connect(self.playbutton.show)
        self.pausebutton.clicked.connect(self.pausebutton.hide)
        self.stopbutton.clicked.connect(self.playbutton.show)
        self.stopbutton.clicked.connect(self.pausebutton.hide)
        self.crossrandom.clicked.connect(self.crossrandom.hide)
        self.crossrandom.clicked.connect(self.randombutton.show)
        self.randombutton.clicked.connect(self.randombutton.hide)
        self.randombutton.clicked.connect(self.crossrandom.show)
        self.crossrepeat.clicked.connect(self.crossrepeat.hide)
        self.crossrepeat.clicked.connect(self.repeatbutton.show)
        self.repeatbutton.clicked.connect(self.repeatbutton.hide)
        self.repeatbutton.clicked.connect(self.crossrepeat.show)
        self.actionExit.triggered.connect(Interface.close)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", "Spytify"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Interface", "Artist"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Interface", "Song"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Interface", "Album"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Interface", "Length"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.library), _translate("Interface", "Library"))
        self.songname.setText(_translate("Interface", "Artist - Music"))
        self.welcometext.setText(_translate("Interface", "Welcome,"))
        self.usertext.setText(_translate("Interface", "User"))
        self.errortext.setText(_translate("Interface", "ErrorMessage"))
        self.searchbutton.setText(_translate("Interface", " Search"))
        self.playingtext.setText(_translate("Interface", "Streaming: Music"))
        self.animationtext.setText(_translate("Interface", "|"))
        self.menuView.setTitle(_translate("Interface", "View"))
        self.menuSettings.setTitle(_translate("Interface", "Settings"))
        self.menuHelp.setTitle(_translate("Interface", "Help"))
        self.menuAction.setTitle(_translate("Interface", "Action"))
        self.actionLogOut.setText(_translate("Interface", "Log Out"))
        self.actionExit.setText(_translate("Interface", "Exit"))

import iconsRC
